/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ConversationParticipantService } from "../conversationParticipant.service";
import { ConversationParticipantCreateInput } from "./ConversationParticipantCreateInput";
import { ConversationParticipant } from "./ConversationParticipant";
import { ConversationParticipantFindManyArgs } from "./ConversationParticipantFindManyArgs";
import { ConversationParticipantWhereUniqueInput } from "./ConversationParticipantWhereUniqueInput";
import { ConversationParticipantUpdateInput } from "./ConversationParticipantUpdateInput";

export class ConversationParticipantControllerBase {
  constructor(protected readonly service: ConversationParticipantService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ConversationParticipant })
  async createConversationParticipant(
    @common.Body() data: ConversationParticipantCreateInput
  ): Promise<ConversationParticipant> {
    return await this.service.createConversationParticipant({
      data: {
        ...data,

        conversation: data.conversation
          ? {
              connect: data.conversation,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        conversation: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [ConversationParticipant] })
  @ApiNestedQuery(ConversationParticipantFindManyArgs)
  async conversationParticipants(
    @common.Req() request: Request
  ): Promise<ConversationParticipant[]> {
    const args = plainToClass(
      ConversationParticipantFindManyArgs,
      request.query
    );
    return this.service.conversationParticipants({
      ...args,
      select: {
        conversation: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ConversationParticipant })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async conversationParticipant(
    @common.Param() params: ConversationParticipantWhereUniqueInput
  ): Promise<ConversationParticipant | null> {
    const result = await this.service.conversationParticipant({
      where: params,
      select: {
        conversation: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ConversationParticipant })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateConversationParticipant(
    @common.Param() params: ConversationParticipantWhereUniqueInput,
    @common.Body() data: ConversationParticipantUpdateInput
  ): Promise<ConversationParticipant | null> {
    try {
      return await this.service.updateConversationParticipant({
        where: params,
        data: {
          ...data,

          conversation: data.conversation
            ? {
                connect: data.conversation,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          conversation: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ConversationParticipant })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteConversationParticipant(
    @common.Param() params: ConversationParticipantWhereUniqueInput
  ): Promise<ConversationParticipant | null> {
    try {
      return await this.service.deleteConversationParticipant({
        where: params,
        select: {
          conversation: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
